=== @defer

=== La nouvelle ère du Lazy Loading  

*@defer* permet de charger le contenu de manière différée, en fonction de différents déclencheurs.

=== !
WARNING: En SSR les *defer* ne seront jamais déclenchées.

=== !

[source,html,linenums, data-id=defer]
----
@defer(condition) {
  <p>Une planète a été chargée.</p>
}
----

=== De multiples déclencheurs

Deux options pour configurer le déclenchement :

* *on*
* *when*

=== Déclencheur on

*on* spécifie une condition à l'aide d'un déclencheur disponible dans Angular.

Il est possible de définir plusieurs déclencheurs d'événements à la fois. 

=== !
[.notes]
****
*viewport* derrière se cache un intersection observer
*interaction* écoute les événements "click" et "keydown".
*hover* écoute les événements mouseenter et focusin.
*timer* en utilisant setTimeout.
****

* *idle* : chargement quand le navigateur est inactif.
* *viewport* : chargement du bloc lorsque l'élément devient visible dans la fenêtre du navigateur. 
* *interaction* : chargement lorsque l'utilisateur interagit avec l'élément.
* *hover* : chargement du bloc lorsque l'utilisateur survole l'élément.
* *immediate* : chargement immédiat de l'élément N'affiche pas de placeholder, même s'il en existe un.
* *timer* : chargement du bloc après une durée donnée.



=== Chargement sur un Timer 

[source,html,linenums, data-id=defer]
----
@defer(on timer(5s))  {
  <p>Une planète a été chargée.</p>
} @placeholder {
  <div>Le chargement va bientôt commencer.</div>
}
----

=== Chargement sur une Interaction 

[source,html,linenums, data-id=defer]
----
@defer (on interaction) {
  <p>Une planète a été chargée.</p>
}
@placeholder {
  <div>Cliquez pour afficher une planète.</div>
}
@loading(minimum 1s) {
  <span>Chargement...</span>
}
----

=== Chargement sur l'entrée dans le Viewport 

[source,html,linenums, data-id=defer]
----
@for (planet of planets; track $index) {
  @defer (on viewport) {
    <p>{{ planet.name}}</p>
  } @placeholder (minimum 2s) {
    <div>Chargement..</div>
  }
}
----

=== Déclencheur when

*when* spécifie une condition sous la forme d'une expression qui renvoie un boolean.

Lorsque cette expression devient vraie, le placeholder est remplacé par l'élément lazy loaded.

=== !
WARNING: Si la condition *when* redevient fausse, le bloc "defer" n'est pas remplacé par le bloc "placeholder". La permutation est une opération unique.

=== !
[source,html,linenums, data-id=defer]
----
@defer (when true) {
  <p>Une planète a été chargée.</p>
}
@loading(minimum 1s) {
  <span>Chargement...</span>
}
----

=== gestion des timing 

Le chargement du bloc *@defer* pouvant être rapide, il existe un risque que le *@loading* soit affiché et masqué trop rapidement, ce qui provoquerait un effet de "scintillement".

=== !
 * *after* pour spécifier après combien de millisecondes le chargement doit être affiché.
 * *minimum* pour spécifier une durée minimale pour le chargement.

=== !

[source,html,linenums, data-id=defer]
----
@defer(on timer(2s)) {
    <p>Une planète a été chargée.</p>
}
@placeholder {
  <div>Le chargement va bientôt commencer.</div>
}
@loading (after 500ms; minimum 1s) {
  <div>Chargement...</div>
}
----

=== Gestion des erreurs 

Le bloc *@error*  permet de déclarer le contenu qui sera affiché si le chargement différé échoue.

=== !

[source,html,linenums, data-id=defer]
----
@defer(condition) {
    <p>Une planète a été chargée.</p>
}
@placeholder {
  <div>Le chargement va bientôt commencer.</div>
}
@loading {
  <div>Chargement...</div>
}
@error {
  <div>Une erreur est survenue.</div>
}
----

=== Et pour les tests ?

[%auto-animate]
=== !
[source,typescript,linenums, data-id=defer-test, highlight=3]
----
beforeEach(() => {
  TestBed.configureTestingModule({
    deferBlockBehavior: DeferBlockBehavior.Playthrough
  });
});
...

await fixture.whenStable();
... 
const deferBlocks = await fixture.getDeferBlocks();
expect(deferBlocks.length).toBe(1);
..
/* Render the defer blocks */
await deferBlocks[0].render(DeferBlockState.Placeholder);
...
await deferBlocks[0].render(DeferBlockState.Loading);
...
await deferBlocks[0].render(DeferBlockState.Complete);
...
await deferBlocks[0].render(DeferBlockState.Error);
----

[%auto-animate]
=== !
[source,typescript,linenums, data-id=defer-test, highlight=8]
----
beforeEach(() => {
  TestBed.configureTestingModule({
    deferBlockBehavior: DeferBlockBehavior.Playthrough
  });
});
...

await fixture.whenStable();
... 
const deferBlocks = await fixture.getDeferBlocks();
expect(deferBlocks.length).toBe(1);
..
/* Render the defer blocks */
await deferBlocks[0].render(DeferBlockState.Placeholder);
...
await deferBlocks[0].render(DeferBlockState.Loading);
...
await deferBlocks[0].render(DeferBlockState.Complete);
...
await deferBlocks[0].render(DeferBlockState.Error);
----


[%auto-animate]
=== !
[source,typescript,linenums, data-id=defer-test, highlight=10;13..20]
----
beforeEach(() => {
  TestBed.configureTestingModule({
    deferBlockBehavior: DeferBlockBehavior.Playthrough
  });
});
...

await fixture.whenStable();
... 
const deferBlocks = await fixture.getDeferBlocks();
expect(deferBlocks.length).toBe(1);
..
/* Render the defer blocks */
await deferBlocks[0].render(DeferBlockState.Placeholder);
...
await deferBlocks[0].render(DeferBlockState.Loading);
...
await deferBlocks[0].render(DeferBlockState.Complete);
...
await deferBlocks[0].render(DeferBlockState.Error);
----
